In [31]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\kunal\AppData\Local\Programs\Python\Python312\Lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\kunal\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\kunal\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\Users\kunal\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\kunal\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\Users\kunal\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

pandas

In [2]:
import pandas as pd
a=pd.Series([10,20,30,25,56])
print(type(a))

<class 'pandas.core.series.Series'>

In [3]:
s1=pd.Series(
    [1,2,3],
        index=['A','B','c']
)
s2=pd.Series(
    [3,2,2],
        index=['A','B','c']
)
print("s1 series:\n",s1)
print("s2 series:\n",s2)

s1 series:
 A    1
B    2
c    3
dtype: int64
s2 series:
 A    3
B    2
c    2
dtype: int64

pandas -data cleaning

In [7]:
import pandas as pd

In [11]:
df=pd.read_csv(r"C:\Users\kunal\Downloads\salary_data.csv")
df

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [12]:
df.head()  #For viewing first rows of data

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [13]:
df.tail()

    YearsExperience    Salary
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [14]:
df.shape

(30, 2)

In [15]:
df.dtypes

YearsExperience    float64
Salary             float64
dtype: object

In [16]:
df.describe()

       YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes

In [18]:
df["Salary"]

0      39343.0
1      46205.0
2      37731.0
3      43525.0
4      39891.0
5      56642.0
6      60150.0
7      54445.0
8      64445.0
9      57189.0
10     63218.0
11     55794.0
12     56957.0
13     57081.0
14     61111.0
15     67938.0
16     66029.0
17     83088.0
18     81363.0
19     93940.0
20     91738.0
21     98273.0
22    101302.0
23    113812.0
24    109431.0
25    105582.0
26    116969.0
27    112635.0
28    122391.0
29    121872.0
Name: Salary, dtype: float64

In [20]:
df[df[].between(5.5,7.2)]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (4032153889.py, line 1)

In [21]:
df.sort_values("Salary")

    YearsExperience    Salary
2               1.5   37731.0
0               1.1   39343.0
4               2.2   39891.0
3               2.0   43525.0
1               1.3   46205.0
7               3.2   54445.0
11              4.0   55794.0
5               2.9   56642.0
12              4.0   56957.0
13              4.1   57081.0
9               3.7   57189.0
6               3.0   60150.0
14              4.5   61111.0
10              3.9   63218.0
8               3.2   64445.0
16              5.1   66029.0
15              4.9   67938.0
18              5.9   81363.0
17              5.3   83088.0
20              6.8   91738.0
19              6.0   93940.0
21              7.1   98273.0
22              7.9  101302.0
25              9.0  105582.0
24              8.7  109431.0
27              9.6  112635.0
23              8.2  113812.0
26              9.5  116969.0
29             10.5  121872.0
28             10.3  122391.0

In [22]:
df.columns=df.columns.str.lower()

In [ ]:
str.strip()  #to remove spaces

In [ ]:
df["Bonus"] = df["Income"] * 0.20

In [24]:
df

    yearsexperience    salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [ ]:
df["Bonus"] = df["Bonus"] + 2000 #update your data

In [26]:
df

    yearsexperience    salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [ ]:
df["salary"] =df["salary"].fillna("unknown values")   #for filling with constant

In [ ]:
df["Income"] = df["Income"].fillna()(df["Income"].mean())    #numerical and data should not contain any outliers

In [ ]:
df["salary"] = df["salary"].fillna()(df["salary"].median())  #numerical and data should contain  outliers

In [ ]:
df["salary"] = df["salary"].fillna()(df["salary"].mode())    #categorical and text kind of data

In [27]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
dtype: bool

In [28]:
df.drop_duplicates(
    subset = ["Income"]
    inplace= True
)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (4060366865.py, line 2)

In [ ]:
df["Income"].unique()

In [ ]:
df["Gender"]= df["Gender"].replace({
"M":"Male",
"F":"Female"
    
})